[package]
name = "rimer"
version = "0.1.0"
authors = ["xFA25E"]
edition = "2018"

[dependencies]
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
dirs = "2.0.2"
clap = "2.33.0"
daemonize = "0.4.1"

[profile.release]
lto = true
codegen-units = 1
# panic = 'abort'
