[package]
name = "rimer"
version = "0.1.0"
authors = ["xFA25E"]
edition = "2018"

[dependencies]
serde = { version = "1.0.116", features = ["derive"] }
serde_json = "1.0.57"
dirs = "3.0.1"
clap = "2.33.3"
daemonize = "0.4.1"

[profile.release]
lto = true
codegen-units = 1
panic = 'abort'
