#+TITLE: Rimer: simple timer

Rimer is a timer that executes commands on every update step.
It can run multiple timers and can be used as countdown or as stopwatch.

* Motivation
  I like pomodoro technique and I like lemonbar. I wanted to track remaining
  pomodoro time on my panel and couldn't find any ready-made solution. I was also
  learning rust, so I decided to write new timer in it (the previous one that I
  used was written in clojure and C).

  Now I have a little script, panel_timer, that rimer calls every 10 seconds.
  It updates lemonbar and my activity.log file when the timer is halted.

  Also, I have another script that provides a rofi-based menu to rimer.
* What it does
  You start server with the following commmand

  ~$ rimer start <command>~

  ~<command>~ will be called every timer step with the following arguments:

  ~<name> <elapsed time> <total time to run> <status>~

  ~<name>~ is used to distinguish different running timers.

  If you run your timer like this:

  ~$ rimer add --name work --duration 3600 --step 5~

  New timer with name ~work~ will be added and it will run 3600 seconds. Every 5
  seconds the ~<command>~ will be called like this:

  ~$ <command> work <elapsed time> 3600 running~

  If you pause the timer

  ~$ rimer pause work~

  Rimer will update ~work~ timer:

  ~$ <command> work <elapsed time> 3600 paused~

  Resume timer:

  ~$ rimer resume --name work~

  The final update will have the status ~halted~. You can explicitly halt your
  timer with halt command:

  ~$ rimer halt --name work~

  You can use your timer as a ~stopwatch~ by setting duration to a maximum
  *unsigned 64 bit integer*. I hope you will never run your stopwatch for a
  period so long :). This keeps implementation simple IMO.

  Other commands are ~report~, ~quit~. ~report~ gives you a list of all
  currently present timers in the same format as described above. ~quit~ tells
  *rimer* to quit daemon.
* Building
  Install rust and cargo. Download this repo and run in the directory:

  ~$ cargo build --release~
* Installation
  You can install it in the cargo's executables directory

  ~$ cargo install --path . --force~
* Todo
** Make single config with structopt
