#+TITLE: Rimer: simple timer

Rimer is a timer that executes commands on every update step.
It can run multiple timers and be used as countdown or as stopwatch.

* Modivation
  I like pomodoro technique and I like lemonbar. I wanted to track remaining
  pomodoro time on my panel and couldn't find any ready solution. I was also
  learning rust, so I decided to write new timer in it (the previous one that I
  used was written in clojure and C).

  Now I have a little script, panel_timer, that rimer calls every 10 seconds.
  It updates lemonbar and my activity.log file when timer is halted.

  Also, I have another script that provides a rofi-based menu to rimer. I might
  publish it later.
* What it does
  You start daemon with a commmand

  ~$ rimer daemon <command>~

  ~<command>~ will be called every timer step with the following arguments:

  ~<name> <kind> <elapsed time> <total time to run> <status>~

  ~<name>~ is used to distinguish different running timers. ~<kind>~ can be
  ~countdown~ or ~stopwatch~.

  If you run your timer like this:

  ~$ rimer remote countdown work --duration 3600 --step 5~

  New countdown timer with name ~work~ will be added and it will run 3600
  seconds. Every 5 seconds the ~<command>~ will be called like this:

  ~$ <command> work countdown <elapsed time> 3600 running~

  If you pause the timer

  ~$ rimer remote pause work~

  Rimer will update ~work~ timer:

  ~$ <command> countdown work <elapsed time> 3600 paused

  Resume timer:

  ~$ rimer remote resume work~

  The final update will have the status ~halted~. You can explicitly halt your
  timer with halt command:

  ~$ rimer remote halt work~

  ~stopwatch~ is the same as ~countdown~ but the ~<total time to run>~ will be a
  maximum *unsigned 64 bit integer*. I hope you will never run your stopwatch
  for a period so long :). I know that it's a hack, but it keeps implementation
  simple IMO.

  Other commands are ~report~, ~quit~ and ~help~. ~report~ gives you a list of
  all currently present timers in the same format as described above. ~quit~
  tells *rimer* to quit daemon.
* Building
  Install rust and cargo. Download this repo and run in the directory:

  ~$ cargo build --release~
* Installation
  You can install it in the cargo's executables directory

  ~$ cargo install --path . --force~
